CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE teams (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	slug TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	description TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
