import { WORKFLOW_TECHNICAL_STATES } from "~shared";

export const WORKFLOW_STATE_TECHNICAL_STATE_OPTIONS = [
	{
		value: WORKFLOW_TECHNICAL_STATES.DRAFT,
		label: 'DRAFT'
	},
	{
		value: WORKFLOW_TECHNICAL_STATES.PUBLISHED,
		label: 'PUBLISHED'
	},
]
