CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE roles (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name TEXT NOT NULL,
	slug TEXT NOT NULL,
	description TEXT,
	team_id UUID NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX roles_team_id_idx ON roles (team_id);
