CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE content_components (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name TEXT NOT NULL,
	slug TEXT NOT NULL,
	hidden BOOLEAN NOT NULL DEFAULT FALSE,
	internal BOOLEAN NOT NULL DEFAULT FALSE,
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	removeable BOOLEAN NOT NULL DEFAULT TRUE,
	component_name TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
