use crate::modules;
use actix_web::web;

pub fn api(cfg: &mut web::ServiceConfig) {
	cfg.service(
		web::scope("/api/v1")
			.service(web::scope("/status").service(modules::core::controllers::status::ping))
			.service(
				web::scope("/auth")
					.service(modules::auth::controllers::auth::me)
					.service(modules::auth::controllers::auth::update)
					.service(
						web::scope("/local")
							.service(modules::auth::controllers::local::login)
							.service(modules::auth::controllers::local::register),
					)
					.service(
						web::scope("/google")
							.service(modules::auth::controllers::google::login)
							.service(modules::auth::controllers::google::callback),
					)
					.service(
						web::scope("/slack")
							.service(modules::auth::controllers::slack::login)
							.service(modules::auth::controllers::slack::callback),
					),
			)
			.service(
				web::scope("/teams")
					.service(modules::teams::controllers::teams::create)
					.service(modules::teams::controllers::teams::find_all)
					.service(modules::teams::controllers::teams::find_one)
					.service(modules::teams::controllers::teams::update)
					.service(modules::teams::controllers::teams::remove)
					.service(
						web::scope("/{team_id}/roles")
							.service(modules::roles::controllers::roles::create)
							.service(modules::roles::controllers::roles::find_all)
							.service(modules::roles::controllers::roles::find_one)
							.service(modules::roles::controllers::roles::update)
							.service(modules::roles::controllers::roles::remove),
					)
					.service(
						web::scope("/{team_id}/iam-policies")
							.service(modules::iam_policies::controllers::iam_policies::create)
							.service(modules::iam_policies::controllers::iam_policies::find_all)
							.service(modules::iam_policies::controllers::iam_policies::find_one)
							.service(modules::iam_policies::controllers::iam_policies::update)
							.service(modules::iam_policies::controllers::iam_policies::remove),
					),
			)
			.service(
				web::scope("/iam-actions")
					.service(modules::iam_actions::controllers::iam_actions::find_all)
					.service(modules::iam_actions::controllers::iam_actions::find_one),
			)
			.service(
				web::scope("/iam-conditions")
					.service(modules::iam_conditions::controllers::iam_conditions::find_all)
					.service(modules::iam_conditions::controllers::iam_conditions::find_one),
			),
	);
}
