use crate::modules;
use actix_web::web;

pub fn api(cfg: &mut web::ServiceConfig) {
	cfg.service(
		web::scope("/api/v1")
			.service(web::scope("/status").service(modules::core::controllers::status::ping))
			.service(
				web::scope("/auth")
					.service(modules::auth::controllers::auth::me)
					.service(modules::auth::controllers::auth::update)
					.service(
						web::scope("/local")
							.service(modules::auth::controllers::local::login)
							.service(modules::auth::controllers::local::register),
					)
					.service(
						web::scope("/google")
							.service(modules::auth::controllers::google::login)
							.service(modules::auth::controllers::google::callback),
					)
			)
			.service(
				web::scope("/sites")
					.service(modules::sites::controllers::sites::create)
					.service(modules::sites::controllers::sites::find_all)
					.service(modules::sites::controllers::sites::find_one)
					.service(modules::sites::controllers::sites::update)
					.service(modules::sites::controllers::sites::remove)
					.service(
						web::scope("/{site_id}/roles")
							.service(modules::roles::controllers::roles::create)
							.service(modules::roles::controllers::roles::find_all)
							.service(modules::roles::controllers::roles::find_one)
							.service(modules::roles::controllers::roles::update)
							.service(modules::roles::controllers::roles::remove),
					)
					.service(
						web::scope("/{site_id}/iam-policies")
							.service(modules::iam_policies::controllers::iam_policies::create)
							.service(modules::iam_policies::controllers::iam_policies::find_all)
							.service(modules::iam_policies::controllers::iam_policies::find_one)
							.service(modules::iam_policies::controllers::iam_policies::update)
							.service(modules::iam_policies::controllers::iam_policies::remove),
					)
					.service(
						web::scope("/{site_id}/content-types")
							.service(modules::content_types::controllers::content_types::create)
							.service(modules::content_types::controllers::content_types::find_all)
							.service(modules::content_types::controllers::content_types::find_one)
							.service(modules::content_types::controllers::content_types::update)
							.service(modules::content_types::controllers::content_types::remove)
							.service(
								web::scope("/{content_type_id}/fields")
									.service(modules::content_types::controllers::fields::create)
									.service(modules::content_types::controllers::fields::find_all)
									.service(modules::content_types::controllers::fields::find_one)
									.service(modules::content_types::controllers::fields::update)
									.service(modules::content_types::controllers::fields::remove),
							)
					)
					.service(
						web::scope("/{site_id}/content-components")
							.service(modules::content_components::controllers::content_components::create)
							.service(modules::content_components::controllers::content_components::find_all)
							.service(modules::content_components::controllers::content_components::find_one)
							// .service(modules::content_components::controllers::content_components::update)
							.service(modules::content_components::controllers::content_components::remove),
					)
					.service(
						web::scope("/{site_id}/assets")
							.service(modules::assets::controllers::assets::upload)
							.service(modules::assets::controllers::assets::find_all)
							.service(modules::assets::controllers::assets::find_one)
					),
			)
			.service(
				web::scope("/iam-actions")
					.service(modules::iam_actions::controllers::iam_actions::find_all)
					.service(modules::iam_actions::controllers::iam_actions::find_one),
			)
			.service(
				web::scope("/iam-conditions")
					.service(modules::iam_conditions::controllers::iam_conditions::find_all)
					.service(modules::iam_conditions::controllers::iam_conditions::find_one),
			),
	);
}
