import './../../styles/main.scss';
import { Darker_Grotesque } from 'next/font/google';
import { ReactNode } from 'react';

const darkerGrotesque = Darker_Grotesque({
	weight: '400',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className={darkerGrotesque.className}>{children}</body>
		</html>
	);
}
