CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE iam_policies (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name TEXT NOT NULL,
	team_id UUID NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX iam_policies_team_id_idx ON iam_policies (team_id)
