# Using official rust base image
FROM rust:1.70.0

# Set the application directory
WORKDIR /app
COPY . .

RUN cargo install --path .

# Install musl-tools to make many crates compile successfully
# RUN apk add --no-cache musl-dev postgresql-dev
# RUN apt add libpq

# Install cargo-watch
RUN cargo install cargo-watch
RUN cargo install diesel_cli --no-default-features --features postgres

# Copy the files to the Docker image
